apiVersion: apps/v1
kind: Deployment
metadata:
  name: wherkil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wherkil
  template:
    metadata:
      labels:
        app: wherkil
    spec:
      containers:
      - image: okteto.dev/wherkil:latest
        name: wherkil
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.anime1st.com"
        - name: Vless_UUID
          value: "62c598d2-893b-4aab-a48b-70c9fece07a4"
        - name: Vless_Path
          value: "/SRK6DHG"
        - name: Vmess_UUID
          value: "62c598d2-893b-4aab-a48b-70c9fece07a4"
        - name: Vmess_Path
          value: "/VBUGZXO"
        - name: Share_Path
          value: "/Share427"
