apiVersion: apps/v1
kind: Deployment
metadata:
  name: partment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partment
  template:
    metadata:
      labels:
        app: partment
    spec:
      containers:
      - image: okteto.dev/partment:latest
        name: partment
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "moviesjoy.to"
        - name: Vless_UUID
          value: "825f7d89-a010-4367-8734-b9626bae32bd"
        - name: Vless_Path
          value: "/rgftuyt"
        - name: Vmess_UUID
          value: "825f7d89-a010-4367-8734-b9626bae32bd"
        - name: Vmess_Path
          value: "/oivtef"
        - name: Share_Path
          value: "/Share320"
