apiVersion: apps/v1
kind: Deployment
metadata:
  name: pround
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pround
  template:
    metadata:
      labels:
        app: pround
    spec:
      containers:
      - image: okteto.dev/pround:latest
        name: pround
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.plex.tv"
        - name: Vless_UUID
          value: "ca2e7c42-5180-494b-b56a-8a44751cdf59"
        - name: Vless_Path
          value: "/AEJ5YH"
        - name: Vmess_UUID
          value: "ca2e7c42-5180-494b-b56a-8a44751cdf59"
        - name: Vmess_Path
          value: "/KJ46GIF"
        - name: Share_Path
          value: "/Share148"
