apiVersion: apps/v1
kind: Deployment
metadata:
  name: cultural
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cultural
  template:
    metadata:
      labels:
        app: cultural
    spec:
      containers:
      - image: okteto.dev/cultural:latest
        name: cultural
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.azmovies.net"
        - name: Vless_UUID
          value: "3f98bee0-8b53-4850-b70e-dd3cf1347456"
        - name: Vless_Path
          value: "/xcukasd"
        - name: Vmess_UUID
          value: "3f98bee0-8b53-4850-b70e-dd3cf1347456"
        - name: Vmess_Path
          value: "/asokrtc"
        - name: Share_Path
          value: "/Share489"
