apiVersion: apps/v1
kind: Deployment
metadata:
  name: lirbery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lirbery
  template:
    metadata:
      labels:
        app: lirbery
    spec:
      containers:
      - image: okteto.dev/lirbery:latest
        name: lirbery
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.anime-planet.com"
        - name: Vless_UUID
          value: "49a2bbda-63cb-4fdb-a0be-155bc59e2090"
        - name: Vless_Path
          value: "/dorjsdeyu"
        - name: Vmess_UUID
          value: "49a2bbda-63cb-4fdb-a0be-155bc59e2090"
        - name: Vmess_Path
          value: "/cvterofg"
        - name: Share_Path
          value: "/Share305"
